query mainQuery {
  categories {
    id
    description
    image
    name
    created_at
    updated_at
  }
  products {
    id
    title
    subtitle
    price
    description
    images
    amount_in_stock
    categories
    created_at
    updated_at
    total_count
    seller {
      id
      email
      last_name
      phone_number
      first_name
      user_name
      shop_type
      shop_name
    }
  }
  
}
