mutation (
  $user_id: uuid!
 
  $address1: String!
  $address2: String!
  $city: String!
  $company_name: String!
  $country: String!
  $kebele: String!
  $sub_city: String!
  $zip_code: Int!
) {
  update_billing_and_shipping_addresses(
    where: { user_id: { _eq: $user_id } }
    _set: {
      address1: $address1
      address2: $address2
      city: $city
      company_name: $company_name
      country: $country
      kebele: $kebele
      sub_city: $sub_city
      zip_code: $zip_code
    }
  ) {
    returning {
      id
    }
  }
  
}
